before_script:
    - apt-get update -qq
    - apt-get install --force-yes libcunit1 libcunit1-doc libcunit1-dev

build:
    stage: build
    script:
        - make

test:
    stage: test
    script:
        - make test
        - make valgrind
